# Generated by Django 3.0.6 on 2020-05-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_check', models.BooleanField()),
                ('todo_item_name', models.CharField(max_length=150)),
            ],
        ),
    ]
