# Generated by Django 3.0.6 on 2020-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='item_check',
            field=models.BooleanField(default=False),
        ),
    ]
