# Generated by Django 3.0.6 on 2020-05-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200518_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='item_check',
            new_name='check',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='todo_item_name',
            new_name='name',
        ),
    ]
